"""auto migration

Revision ID: a98d53db6d7f
Revises: d931c6060557
Create Date: 2026-01-18 13:37:42.717308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98d53db6d7f'
down_revision: Union[str, Sequence[str], None] = '6708665ab3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_message_chat_created_id_desc', 'message', ['chat_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_chat_created_id_desc', table_name='message')
    # ### end Alembic commands ###
